### ISSUE TITLE
dd doesnt work with long string

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#16]
When you enter in insert mode SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
and then try to 'dd', you get an IndexError. Not quite clear how urwid handels long string and linebreaks.

**Comment by JNicL** [comment]
dd behaves in the situation
sssssss\n
\n
asdasdasd

when the cursor is in the first row. Due to the '\n' the cursor jumps to the third row after dd as the previous x-value is higher than.

**fixed**

**Comment by bijancn** [comment]
No this is not fixed. Insert the exact string of 'SSS' as shown above and press 'dd' and you get

```
Traceback (most recent call last):
  File "ez_cli.py", line 822, in <module>
    loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 669, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 706, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 390, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 490, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1124, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 839, in keypress
    return self._original_widget.keypress((maxcol,maxrow-top-bottom), key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 2265, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1583, in keypress
    key = self.focus.keypress(tsize, key)
  File "ez_cli.py", line 545, in keypress
    self.command_dict[key]()
  File "ez_cli.py", line 460, in cmd_delete
    text.pop(y-2)
IndexError: pop index out of range
```
